/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleProject;

import java.util.Scanner;

public class Library {
    public static void main(String args[]){
    	@SuppressWarnings("resource")
    	Scanner sc = new Scanner(System.in);
    	System.out.println("enter the first no");
    	int a = sc.nextInt();
    	System.out.println("enter the second no");
    	int b = sc.nextInt();
    	System.out.println("Addition is: "+ (a+b));
    }
}
